baseURL = "http://apicv.es/"
languageCode = "es-es"
title = "APICV"
publishdir = "docs"

theme = "prologue"

[params]
  name = "APICV"
  description = "Página web de la APICV"
  copyright = "@APICV"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/apicv"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/apicv"

[[params.social]]
  medium = "telegram"
  icon = "telegram"
  link = "https://t.me/apicv"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:presidente@apicv.es"

# Portfolio column one

[[params.portfolio1]]
  title = "Un poco de historia"
  alt = ""
  tam=500
  source = "img/historia.jpg"
  url = "https://view.genial.ly/5e1db0229e64014072a0fcff/vertical-infographic-timeline-apicv"



# Portfolio column two

[[params.portfolio2]]
  title = "Últimas noticias"
  alt = ""
  tam=500
  source = "img/pic04.jpg"
  url = "#"



# Portfolio column 3

[[params.portfolio3]]
  title = "La APICV en Redes Sociales"
  alt = ""
  tam=500
  source = "img/pic06.jpg"
  url = "#"


